version: '3'
services:
  db:
    image: postgres:16.3-alpine3.18
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    shm_size: 128mb
    volumes:
       - postgres:/data/postgres
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
volumes:
  caddy_data:
  caddy_config:
  postgres: